### ISSUE TITLE
Receive set temperature and ACTUAL temperature with mqtt - Soll-Temperatur und IST-Temperatur empfangen mit mqtt

### ISSUE THREAD

**Issue by zillawilli** [Lenti84/VdMot_Controller#100]
Hello togetherness

I have a questions please

Is it possible with the current software to receive the setpoint temperatures of each room via mqtt?
Also the ACTUAL temperatures?

I would install in each roomt an ESP32 as a thermostat which sends the set and actual temperature via mqtt to the software.

greetings
zillawilli

Hallo Miteinander

Ich habe bitte eine Frage

Ist es mit der momentanen Software möglich, die Soll-Temperaturen der einzelnen Räume über mqtt zu empfangen?
Ebenso die IST-Temperaturen?

Ich würde in jedem Raumt einen ESP32 als Thermostat einbauen welcher die Soll- und Ist-Temperatur per mqtt an die Software sendet.

schöne Grüße
zillawilli

**Comment by SurfGargano** [comment]
Hi,
Du brauchst einen MQTT Server, der Dir dann alle Soll/Ist Werte sendet. Mehrere Mqtt Verbindungen sind nicht möglich.
Du kannst über JSON Interface mehrere Verbindungen gleichzeitig machen und die Soll / Ist Werte jedes einzelnen Raumes schicken. (also Connecten-Werte schicken-Verbindung schließen) Jedoch weiß ich nicht ob das System bei größerer Anzahl Verbindungen instabil wird.
