### ISSUE TITLE
MQTT Retain ?

### ISSUE THREAD

**Issue by TTr0n** [Lenti84/VdMot_Controller#103]
Wäre es möglich, die Werte vom Controller als "Retain" zu senden oder zumindest die Option als Schalter zur Verfügung zu stellen?

**Comment by SurfGargano** [comment]
OK, wird mit der nächsten Version enthalten sein, konfigurierbar.

**Comment by TTr0n** [comment]
Danke, habs gerade eingespielt und werde berichten.
Ist die FW für den STM noch auf Stand 1.2.2 ? Denn da hat sich in der Anzeige nichts geänder, da steht immer noch 1.2.2 vom 09.08.

**Comment by SurfGargano** [comment]
Stm 1.2.2 ist die aktuelle Version

**Comment by TTr0n** [comment]
Sorry, hab vergessen eine Rückmeldung zu geben. 
Sieht so aus, als wenn alles wie erwartet funktioniert!
Vielen Dank!

**Comment by SurfGargano** [comment]
Frage : wofür brauchst Du das retain?
