### ISSUE TITLE
Fensterkontakt per mqtt

### ISSUE THREAD

**Issue by Alfons-Hetler** [Lenti84/VdMot_Controller#109]
Ein Externer Fensterkontakt per Mqtt der den controller direkt anspricht um das Ventil zuzufahren wäre toll.

Derzeit mache ich es über einen Fensterkontakt der dann das stellsignal auf 0 grad setzt.
Geht, aber nicht schön aufgrund der eingestellten Verzögerung.

Fenster auf: Zwangstellung Ventil 0%, sowie blocken neuer Tempwerte (auch über mqtt)
Fenster zu: Optionen: alten Wert wieder annehnen oder aus bleiben und manuell wieder einschalten.
Wenn man die 2 Optionen wählen könnten wäre das top.

**Comment by SurfGargano** [comment]
Zum Testen auf : https://github.com/SurfGargano/VdMot_Controller/tree/developer/releases/1.2.4_Dev
Es werden 2 Mqtt Objekte unter window angelegt : 
state : 0 = Fenter geschlossen, 1 = Fenster offen
target : Ventilstellung bei geöffnetem Fenster.
Bei Fenster öffnen wird das Ventil sofort auf den Wert gesetzt, bei Fenster schließen erst mit Aufruf des nächsten Zyklus ( abhängig von Ts)
