### ISSUE TITLE
Uptime Topic MQTT not send or only 1 time at startup

### ISSUE THREAD

**Issue by Alfons-Hetler** [Lenti84/VdMot_Controller#110]
Uptime wird nicht per MQTT gesendet oder in Abständen die ich nicht nachvollziehen kann.
Am Anfang wird es einmal gesendet dann nicht mehr aktualisiert.

![Screenshot 2023-11-09 183432](https://github.com/Lenti84/VdMot_Controller/assets/72218275/573002d1-e38c-4c53-a511-80018adbd115)

![Bild_2023-11-09_183530984](https://github.com/Lenti84/VdMot_Controller/assets/72218275/ee75127f-f52c-4ccf-a728-935e8f9415b6)

![192 168 178 234_#config_1](https://github.com/Lenti84/VdMot_Controller/assets/72218275/f72f81b7-47ab-47e9-a352-40b0c31e1438)

**Comment by SurfGargano** [comment]
Solved with V1.3.0
