### ISSUE TITLE
WLAN don´t reconnect

### ISSUE THREAD

**Issue by WFeneberg** [Lenti84/VdMot_Controller#111]
My Controller disconnect from WLAN if it is running longer. Only a hard reboot reconnect to the Router.
It was on Version 1.2.2 Dev.

I try to find out how long it need that the controller disconnect.

I updated to Gargano 1.25 Dev hope this helps

**Comment by SurfGargano** [comment]
Automatic wifi reconnect is implemented in V1.3.0 (coming soon)
