### ISSUE TITLE
Gargano Update 1.2.5 Dev

### ISSUE THREAD

**Issue by WFeneberg** [Lenti84/VdMot_Controller#112]
I updated the WT32 to Verson 1.2.5 Dev it works. But for the STM it show after the Update the last Version 1.2.2 DEV. I have a C1 Board.

The Update is working normal and show Finished. ????? 

Thanks.

**Comment by SurfGargano** [comment]
1.2.2 is the last Version for STM. STM is not updated if there is no modification.
