### ISSUE TITLE
Aktuelle IP Adresse bitte in MQTT mit aufnehmen

### ISSUE THREAD

**Issue by P7aM5qzEddT66lE** [Lenti84/VdMot_Controller#129]
Aktuell wird die IP Adresse nicht per MQTT versendet.
Eine Übertragung hätte Vorteile in der Überwachung, ob der entsprechende VdMot.Controller noch am Netz ist und in der Wartung des selbigen.

Danke im voraus,
Günter

**Comment by SurfGargano** [comment]
Implemented in 1.4.4
