### ISSUE TITLE
WT32 Network cannot be changed without STM32 attached.

### ISSUE THREAD

**Issue by Funkenschuhster** [Lenti84/VdMot_Controller#136]
Case:
Without STM32 connection, it is not possible to save any settings. 

Problem:
In case the WT32 is messed up, router, ethernet cable, programmer, laptop has to be arranged in front of the controller to flash/configure.

Recommendation: 
Extra save button for network settings.

**Comment by SurfGargano** [comment]
Fixed in V1.4.7
