### ISSUE TITLE
Remanence for valve posisition

### ISSUE THREAD

**Issue by Funkenschuhster** [Lenti84/VdMot_Controller#137]
Case:
In case the controller is reset, all valves start at the same preset level. Then the control will take over.

Problem:
My floor heating takes hours to reset to normal temperature. The comfort of the rooms is disordered for quite some time.

Recommendation:
Add remanence for valve position. After reset, the valve will go to last known position.
Or: Add option to set individual start position for each valve.

**Comment by SurfGargano** [comment]
Last position is not possible,  too many write operations to the flash will damage it.

**Comment by SurfGargano** [comment]
Closed

**Comment by Funkenschuhster** [comment]
What about storing the remanence in the MQTT?
