### ISSUE TITLE
Valve manual override

### ISSUE THREAD

**Issue by Funkenschuhster** [Lenti84/VdMot_Controller#138]
With my industrial background, I miss one function:

Case:
1. Set a control loop to manual.
2. Change valve manually to some position
3. Set the control loop to automatic.
--> The valve will move to last automatic control position

Suggestion:
If a control loop is in manual mode, the valve can be adjusted.
When the control loop is set to automatic, it will start control from the actual valve position.
--> smooth transition.

**Comment by SurfGargano** [comment]
Not possible in control logic.

**Comment by SurfGargano** [comment]
Closef
