### ISSUE TITLE
ESP32 User Interface - More temperature sensors than valves

### ISSUE THREAD

**Issue by xal88** [Lenti84/VdMot_Controller#16]
Hello,
Usecase:  8 Valves, 10x Onewire sensor  ( one for each valve, plus one for manifold input and output )

* How will this look like in the status page ?

* Config page needs a mapping from Onewire_ID to Name and valve
   STM32 command list ist talking of 36 possible Temperature sensors  
  ``` stsnx x y:    |   set first 1-wire sensor index y to valve x    |     x=0...11, y=0...35```
 
   And why are there 2 commands [ stsnx | stsny ], as there is only one 1-wire bus?
 
Thanks, and keep up your great work
regards

**Comment by Lenti84** [comment]
Hi xal88,

this can look like following picture, but with more entries for each item:
![grafik](https://user-images.githubusercontent.com/72278363/151251219-6abaf28b-b36a-4989-896d-966013bc0849.png)

Config page can now connect sensors to valves and sensor count was corrected.

There are two commands. One for first temp sensor assigned to valve x and one for second temp sensor assigned to valve x. Temp sensors are all connected to the same 1-wire bus.
