### ISSUE TITLE
Information how to order

### ISSUE THREAD

**Issue by wendy2702** [Lenti84/VdMot_Controller#23]
Hi,

can you provide some information on how to order and costs?

**Comment by Lenti84** [comment]
I recently put the board on tindie:
https://www.tindie.com/products/lenti/vdmot_controller/

Please have a view for scope of delivery, order information and costs.

**Comment by Lenti84** [comment]
Hello everybody! Boards are now available via Tindie.

**Comment by dreitakter** [comment]
The THT Parts are Not available in the Store.
I want to buy two complete Kits. Will this be possible soon or are These the Last parts that you sell?

**Comment by Lenti84** [comment]
New/more THT parts will be available at the end of next week.

**Comment by dreitakter** [comment]
Nice. Remind me when the parts are available. Thank you :)

**Comment by Lenti84** [comment]
Last few parts for 2022 available at Tindie. 
New parts will probably be available from january 23.

**Comment by uplight-dev** [comment]
I'm not sure but is Tindie the only option to build this board(i.e. closed source)?
Or can I print this board myself to pcbway.com or similar?

Thanks!

**Comment by Lenti84** [comment]
At the moment there are non plans to fully publish hardware sources (Gerber...).
But the full schematic, some description and BOM you can already find in GitHub.
As the project was not created in EasyEda, I will not port it.
Kind regards

**Comment by Lenti84** [comment]
New boards, THT parts, BlackPill Boards and some WT32-ETH01 boards are back in stock at Tindie.

Check out https://www.tindie.com/products/lenti/vdmot_controller/
![board](https://user-images.githubusercontent.com/72278363/213816673-743d7e41-65e4-46bc-a954-5a390d48a2aa.jpg)

**Comment by Lenti84** [comment]
Moved information to: https://github.com/Lenti84/VdMot_Controller/wiki/FAQ/
