### ISSUE TITLE
ESP32 compile fails, please provide all BINs

### ISSUE THREAD

**Issue by xal88** [Lenti84/VdMot_Controller#31]
Hello, 
asembled the kits last weekend, but could not compile via VSC Platformio. (C++ errors )

Could you please add the additional needed BIN-files for flashing the ESP32, so that I can use esptool.py without compiling?
(or did you pack all the files into your firmware.bin, so I could upload to address 0x1000 ?)

e.g.
```
esptool.py --chip esp32 --port COM4 --before default_reset --after hard_reset write_flash -z --flash_mode dio --flash_freq 40m /
            --flash_size detect /
            0x1000 bootloader_dio_40m.bin  /
            0x8000 partitions.bin /
            0xe000 boot_app0.bin / 
            0x10000 firmware.bin 
```

Erasing is working so far, so the system looks OK..
```
esptool.py --port COM4 erase_flash
    esptool.py v2.8
    Serial port COM4
    Connecting......
    Detecting chip type... ESP32
    Chip is ESP32D0WDQ5 (revision 1)
    Features: WiFi, BT, Dual Core, 240MHz, VRef calibration in efuse, Coding Scheme None
    Crystal is 40MHz
    MAC: 8c:ce:4e:94:82:dc
    Uploading stub...
    Running stub...
    Stub running...
    Erasing flash (this may take a while)...
    Chip erase completed successfully in 14.0s
```

Thanks for your help
Alfred

 
[202206071941_VSCcompile.log](https://github.com/Lenti84/VdMot_Controller/files/8855383/202206071941_VSCcompile.log)

**Comment by xal88** [comment]
fixing resolution to int in helper.cpp at least makes it to compile and run...
```
String ConvBinUnits(size_t bytes, byte resolution) 
{
  if  (bytes < 1024) {
    return String(bytes) + " B";
  }
  else if (bytes < 1024 * 1024) {
    return String(bytes / 1024.0,  int(resolution)) + " KB";
  }
  else if (bytes < (1024 * 1024 * 1024)) {
    return String(bytes / 1024.0 / 1024.0, int(resolution)) + " MB";
  }
  else return "";
}
```

**Comment by Lenti84** [comment]
I added information for flashing ESP32 to https://github.com/Lenti84/VdMot_Controller/blob/master/assembly_kit/installation.md.
Bin files can be found at https://github.com/Lenti84/VdMot_Controller/tree/master/software_esp32

Firmware fix will be added soon to developer branch.

**Comment by xal88** [comment]
could upload the provided .bin-files with ESP_Tools. VdMot is working now.
Would be great if you place **partitions.bin** in the same location ( had to take it from my VSC Platformio files )

The STm upload instructions should close with something like
* 11 Wait for upload finishes
* 12 remove X20 connection
* 13 ( reboot?)
