### ISSUE TITLE
1-Wire not seeing all DS18B20

### ISSUE THREAD

**Issue by xal88** [Lenti84/VdMot_Controller#37]
Some sensors are not detected by scan, others detected but no data.
GUI/config scan gives different results to the scans when booting.
Some sensor delivers data, if manually eintered ID in GUI/config

All sensors are tested and working with ESP PIN and 4k7 Ohm resistor. 
Sensor answer is on the bus, but not picked up to i2c?

### Signaling on oszilloscope comparing ESP and VdMot looks ok.
![3c-4e_ESP_scan](https://user-images.githubusercontent.com/53332864/175254692-8f8b29df-9786-443d-85b5-2b3718ee1192.jpg)

![3c-4e_VdMot_scan](https://user-images.githubusercontent.com/53332864/175254700-38e1b562-e6db-44a8-9efc-1c69c0ad5b9b.jpg)

### Logic compare "-22"  sensor detected, but no data,
ESP test sample OK
![3c-22_logic_ESP_OK](https://user-images.githubusercontent.com/53332864/175256602-b92e524e-ae3c-4bba-8e0b-a717fe4a0863.jpg)
VdMot
![3c-22_logic_VdMot_noData](https://user-images.githubusercontent.com/53332864/175256675-926f3544-27fc-4a2c-b7df-2fff781eb38d.jpg)

### Logic compare "a9" sensor not detected
ESP Test sample OK
![3c-a9_logic_ESP_answer](https://user-images.githubusercontent.com/53332864/175257210-9ba5dd84-3d45-40c4-931d-18423ce21127.jpg)
VdMot test
![3c-a9_logic_VdMot](https://user-images.githubusercontent.com/53332864/175257525-0bb8baf5-da5a-4d0b-b140-0f2586c61bb1.jpg)

**Comment by Lenti84** [comment]
If you compare the oscilloscope shots from ESP and STM you can recognize, that the voltage level with STM32 is not perfectly correct. 
This is a flaw in the STM32 version of arduino 1-wire lib. But for my config it is working fine for currently 10 sensors.

I have tested a fix some time ago. I think it was in OneWire_direct_gpio.h
Instead of a PushPull output
`#define DIRECT_MODE_OUTPUT(base, pin)   pin_function((PinName)pin, STM_PIN_DATA(STM_MODE_OUTPUT_PP, GPIO_NOPULL, 0))`
a change to OpenDrain changed the voltage level problem
`#define DIRECT_MODE_OUTPUT(base, pin)   pin_function((PinName)pin, STM_PIN_DATA(STM_MODE_OUTPUT_OD, GPIO_NOPULL, 0))`

Maybe give it a try if this changes something.
I think i will integrate that in one of the next releases...

**Comment by SurfGargano** [comment]
I have checked with 15 sensors and the modification in V1.05 of stm software: changing from push-pull to open drain.
It works.

**Comment by xal88** [comment]
Thanks. Tried to compile the stm-1.05 with VSC/platformio, result is only 52 kB, old one was 198kB.
With esp32_1.02 and esp32_1.04 the file is growing from  1012->1128 kB.
Can this be right, could you maybe upload the stm firmware 1.05?

**Comment by SurfGargano** [comment]
yes, 52 kB for stm 1.0.5 is correct The old one was about 48 kB
the esp file is 1106 kB with V1.0.5
I have uploaded the stm bin files in the bin directory in developer branch in my repo.
https://github.com/SurfGargano/VdMot_Controller/tree/developer/software_stm32/bin/v1.0.5

**Comment by xal88** [comment]
WTH32 is at 1.05. OTA worked.
Tried to update the STM32 from 1.02 to 1.05.  
Upload of the file ok, but after selecting file, and clicking "Update STM32 now" the progress bar goes to 5%, and then "error". 
Self comiled firmware.bin or development branch same issue.
What am I doing wrong?

**Comment by SurfGargano** [comment]
Pls try following : Format the spiffs by clicking the Format Button in Config section of the wth32. Upload stm bin file again and start the update of stm.Am 13.11.22, 21:14 schrieb Alf ***@***.***>:

   
  WTH32 is at 1.05. OTA worked. Tried to update the STM32 from 1.02 to 1.05. Upload of the file ok, but after selecting file, and clicking "Update STM32 now" the progress bar goes to 5%, and then "error". Self comiled firmware.bin or development branch same issue. What am I doing wrong?

**Comment by xal88** [comment]
Tried on 2 different VdMot boards, firefox or chrome, with WT32 on 1.05.
"/config/Format FS" gives no status update, just reboot. Uploaded Files are gone afterwards.
"update/ST32" gives 5%, than error and reboot.
Syslog atomic shows no useful messages, only the ones about the valve positions.
What else can I do - Blackpill update via external serial?

**Comment by SurfGargano** [comment]
After Format the file info on the config page should be invisible. Is the stm still working?What does the serial debug of wt32 says?Am 14.11.22, 12:12 schrieb Alf ***@***.***>:

   
  Tried on 2 different VdMot boards, firefox or chrome, with WT32 on 1.05. "/config/Format FS" gives no status update, just reboot. Uploaded Files are gone afterwards. "update/ST32" gives 5%, than error and reboot. Syslog atomic shows no useful messages, only the ones about the valve positions. What else can I do - Blackpill update via external serial?

**Comment by Lenti84** [comment]
Have you tried initial flash with Pressung boot0 button in BlackPill Board? 

https://github.com/Lenti84/VdMot_Controller/blob/master/assembly_kit/installation.md#initial-stm32-flash-via-vdmot-controller

**Comment by xal88** [comment]
update to 1.05_Dev initial flash did work, thanks for your help.
Connected 32 senors ( all I have ), found all - even the cheap chinese problematic ones.
Will close the issue.
