### ISSUE TITLE
Cable length to actors

### ISSUE THREAD

**Issue by dreitakter** [Lenti84/VdMot_Controller#50]
Hi.
Do you have any Idea which cable length is possible between the Controller Board and the actors?

**Comment by SurfGargano** [comment]
I have 10 meters from controller to 2 actors installed. It works without problems. I used shielded KNX kable ( 4x 0.8 mm²).

**Comment by Lenti84** [comment]
Moved information to: https://github.com/Lenti84/VdMot_Controller/wiki/FAQ
