### ISSUE TITLE
ESP32 with Lan

### ISSUE THREAD

**Issue by Elluminatus** [Lenti84/VdMot_Controller#55]
Hi I‘m wondering if there could be a esp32 with Lan possible on the board? Thank you for your help

Greetings Thomas

**Comment by Elluminatus** [comment]
Oh I saw that the C Sample has a Lan Port available

**Comment by SurfGargano** [comment]
The esp32 we used is the WT32 - ETH01. Thie module has wifi and eth on board.

**Comment by Elluminatus** [comment]
Thank you very much. I send you some questions via Tindie, maybe you can contact me.

 


Gesendet: Mittwoch, 4. Januar 2023 15:56
An: Lenti84/VdMot_Controller ***@***.***>
Cc: Elluminatus ***@***.***>; Author ***@***.***>
Betreff: Re: [Lenti84/VdMot_Controller] ESP32 with Lan (Issue #55)

 

The esp32 we used is the WT32 - ETH01. Thie module has wifi and eth on board.

**Comment by Lenti84** [comment]
Your welcome. See my answers at Tindie. Kind regards.
