### ISSUE TITLE
Config and Control sections

### ISSUE THREAD

**Issue by bluephoenix28** [Lenti84/VdMot_Controller#61]
Could please explain the meaning of some of the fields in the Control and in the Config section?

**Control page**:
- What does Xp, Offset, Ti, Ts mean? I guess Ti and Ts are the parameters of the PI controller, but the rest...?
- What is the difference between dynamic ki and static ki?
- How can I determine the Active zone? Do I need to extract the current values for, as in your measurements for the two different valves?
- What does happen in the manual heat control mode? Is Xp the dedicated position for that?

**Config page**:
- What do the Characteristic values in the Motor section mean?

**Comment by SurfGargano** [comment]
Xp is the constant part of the proportional value (kp = 100/ Xp)
Offset is a constant temperature offset , that is added to the measured temperature value
Ti is the integral value of the I – part
Ts is the samplig time in seconds, that starts the next calculation.

Dynamic ki means that the I – part will be calulated with the proportional value  (kp*e, e = new difference from target-temp value)
Dynamic is more quick when the difference is greater.
Static ki means that the I-part will be calcuated with a constant ki – value.
HeatControl:
Manual : 
The Pi- Controller is disabled, no Calculation will be executed . You can control the valves by yourself. (setting the target position in the status page or via mqtt)
On : 
The Pi- Controller is enabled,
Off : 
The Pi_Controller is disabled and the valves goes to the park position. Useful in summer.

Determinate the active zone is not trivial. With 100 % valve position you may have a relaxed position of the valve. You now decrease the valve postion until the valve is solid.
 
Characteristic values in the Motor section:
Low, High : Detection for end low position of the motor. This is calulated by the mean current (mA) oft he motor multiplied with the low/high value.
e.g Low value = 2.0
The motor draws electricity normally 20mA. So the endposition is detected when he draws  
20* 2.0 = 40 mA.
The same for high value, the other endposition.
