### ISSUE TITLE
3d stl file

### ISSUE THREAD

**Issue by bluephoenix28** [Lenti84/VdMot_Controller#69]
Hi,
I am currently working on a housing to be 3D-printed and it would be helpful to have a 3D file of the assembled PCB. Is it possible to provide a stl file or some other format, I can import into Freecad?

**Comment by Lenti84** [comment]
Would a step .stp file help? This is supported by my toolchain for sure. FreeCAD can read step.

**Comment by bluephoenix28** [comment]
Hi, yes step ist totally fine! Thanks.

**Comment by Lenti84** [comment]
Please have a look at https://github.com/Lenti84/VdMot_Controller/blob/master/hardware/c3-sample_3D.rar

Please consider measure tolerances of piggyback boards and connectors.

**Comment by bluephoenix28** [comment]
Perfect
