### ISSUE TITLE
Description and function of the input fields

### ISSUE THREAD

**Issue by zillawilli** [Lenti84/VdMot_Controller#72]
Hello togetherness

Is there a description regarding the function of each input field please?

Hallo Miteinander

Gibt es eine Beschreibung bezüglich der Funktion der einzelnen Eingabefelder bitte?

Thank you
willi

**Comment by Lenti84** [comment]
Hi, I have started to use the wiki right now. Hope i can fill it in the next time.

https://github.com/Lenti84/VdMot_Controller/wiki
