### ISSUE TITLE
Linked valves not synchronously parked when control is disabled

### ISSUE THREAD

**Issue by elektronikworkshop** [Lenti84/VdMot_Controller#73]
Hi Lenti,

I just set up my system and it will produce most probably some more bug reports than this, because it's huge and comes with different corner cases. But that's good - it will lead to a more reliable system. And if I have some spare time I can contribute to the development as well. That all said, lets get to the first bug report:

I've configured my system such that I can check the status of my two circulation pumps. One pump drives three VdMots and the other two. When I detect that one of the pumps is disabled (during the night) I disable the regulation by the corresponding VdMot. This is to prevent a) noise and b) unnecessary wear of the valves.

![Screenshot 2023-02-27 at 20-46-28 Node-RED](https://user-images.githubusercontent.com/21954933/221667808-de7609aa-1194-40ad-b36c-78a8275d17b3.png)

When I got it up and running I discovered that only the main valve gets parked when the controller is disabled. All the linked valves stay in their original position. I'm showing here only one controller, but the other behaves the same:

<img src="https://user-images.githubusercontent.com/21954933/221668546-838b8278-e59c-46cc-ad90-33ad3048194e.png" width="40%">
<img src="https://user-images.githubusercontent.com/21954933/221668549-f874a8b9-18ff-4260-8678-3222fa19437a.png" width="55%">

I would assume that this is not the desired behavior. Desired/expected behavior would be in my understanding, that all valves move to the parked position.

Regards!
EW

**Comment by SurfGargano** [comment]
Is fixed in 1.1
