### ISSUE TITLE
Falsche Hardware / Software Zuordnung Ventile RJ45 Buchse

### ISSUE THREAD

**Issue by Alfons-Hetler** [Lenti84/VdMot_Controller#95]
Wenn man nur ein Stellantrieb auf 1 steckt wird dieser unter Stellantrieb 2 im Browser erkannt.

Hardwareport 1 ist Software Port 2.

V1 - No 2
V2 - No 1
V3 - No 4
V4 - No 3
V5 - No 6
V6 - No 5
V7 - No 8
V8 - No 7
V9 - No 10
V10 - No 9
V11 - No 12
V12 - No 11

Die Ports Zuordnung sind im allgemeinen etwas durcheinander.

Version 1.0.8 Beta und 1.2.2 DEV

Tritt bei beiden auf.

**Comment by Lenti84** [comment]
Hi Alfons,

if you have D-H0044-01-05 hardware, please use C2 firmware file (STM32_C2_firmware.bin) for STM32.
Otherwise valves will be exchanged: 1<->2, 3<->4, 5<->6 and so on.

Kind regards

**Comment by Alfons-Hetler** [comment]
Thats was my Problem. Thanks now it worked.
