### ISSUE TITLE
Wrong Port speed in Manual/Pictures for flash ESP32

### ISSUE THREAD

**Issue by Alfons-Hetler** [Lenti84/VdMot_Controller#96]
For flash the ESP32 Board is a wrong speed in the online Manual.
That was the reason why i cant initial flash the Board.
Correct speed setting: 921600
I use a CH340 to flash.

**Comment by Lenti84** [comment]
I think there is no right or wrong baudrate for the "flash download tool" as shown in https://github.com/Lenti84/VdMot_Controller/blob/master/assembly_kit/installation.md

I have already used successfully a lot of different baudrates, like:  230400, 460800, 576000 or 921600.

But my experience is also, that sometimes it will not work and after changing the baudrate it does.

**Comment by Alfons-Hetler** [comment]
I try it too and it did not worked.
It says: Custom element doesn´t exist: plothy-graph.
I deleted the app and begin from new but the error stay there.
