### ISSUE TITLE
No issue, Option turn off the LED's on the 2 Boards

### ISSUE THREAD

**Issue by Alfons-Hetler** [Lenti84/VdMot_Controller#97]
Can we add a Option to turn off the LED's in the 2 Boards. The blinking LED is really bad if you dont use the board in a Case.

**Comment by Alfons-Hetler** [comment]
Ich schieb das nochmal nach oben ne ;-) Wenns nicht zu viel mühe macht wäre es schön wenn man das mal einarbeiten könnte.

**Comment by SurfGargano** [comment]
Led's auf dem WTH sind fest verdrahtet und können nicht abgeschaltet werden. Auf dem STM ist das Blinken in der 1.3.2 geändert worden in ein Blitzen. 3s off / 100ms on
