### ISSUE TITLE
No issue, Only Information: i become a new Board revision, the last is now D-H0044-01-05

### ISSUE THREAD

**Issue by Alfons-Hetler** [Lenti84/VdMot_Controller#99]
My Board D-H0044-01-05 shipped 20.09.2023.
What is the different to the old Board Design?

**Comment by Lenti84** [comment]
D-H0044-01-05 has following changes:
- minor changes in the silk screen for better readabillity
- added reset circuit for ESP32, should improve rare startup problems of ESP32 depending on used power supply

Will add that later to the information in https://github.com/Lenti84/VdMot_Controller/blob/master/hardware/assembly_kit.md

**Comment by Alfons-Hetler** [comment]
Thanks.
